#!/usr/bin/python3
# The purpose of lp-to-jira is to take a launchad bug ID and
# create a new Entry in JIRA in a given project


import sys
import os
import json

from optparse import OptionParser

from launchpadlib.launchpad import Launchpad
from jira import JIRA
from jira_api import jira_api


pkg_to_component = {
    "nplan": "netplan",
    "netplan.io": "netplan",
    "netplan": "netplan",
    "systemd": "systemd",
    "s390-tools": "IBM",
    "subiquity": "subiquity",
    "curtin": "subiquity",
    "ubuntu-image": "Ubuntu Image",
    "shim-signed": "Secure Boot",
    "openjdk-lts": "OpenJDK",
    "apt": "Package Management",
    "aptdaemon": "Package Management",
    "ubuntu-release-upgrader": "Package Management"
}
default_component = "Distro"


def getLpBug(lp, bug_number):
    """Make sure the bug ID exists, return bug"""

    bug = None
    try:
        bug = lp.bugs[bug_number]
    except Exception:
        print("Couldn't find the Launchpad bug {}".format(bug_number))
        sys.exit(1)

    return bug


def getLpBugPkg(lp, bug):
    """From a LP bug, get its package"""

    bug_pkg = None
    if len(bug.bug_tasks) == 1:
        bug_pkg = bug.bug_tasks[0].bug_target_name.split()[0]
    else:
        for task in bug.bug_tasks:
            if "(Ubuntu)" in task.bug_target_name:
                bug_pkg = task.bug_target_name.split()[0]

    return bug_pkg


def isBugInJira(jira, bug, project_id):
    """Checks Jira for the same ID as the Bug you're trying to import"""

    existing_issue = jira.search_issues(
        "project = \"{}\" AND summary ~ \"LP#{}\"".format(project_id, bug.id))

    if existing_issue:
        print("Launchpad Issue {} is already logged "
              "in JIRA here {}/browse/{}".format(
                  bug.id,
                  jira.client_info(),
                  existing_issue[0].key))
        return True
    return False


def buildJiraIssue(lp, bug, project_id):
    """Builds and return a dict to create a Jira Issue from"""

    # Get bug info from LP
    bug_pkg = getLpBugPkg(lp, bug)

    # Build the Jira Issue from the LP info
    issue_dict = {
        'project': project_id,
        'summary': 'LP#{} [{}] {}'.format(bug.id, bug_pkg, bug.title),
        'description': bug.description,
        'issuetype': {'name': 'Bug'}
    }

    jira_component = []
    jira_component.append(
        {"name":pkg_to_component.get(bug_pkg, default_component)})
    issue_dict["components"] = jira_component
    
    return issue_dict


def createJiraIssue(jira, issue_dict, bug):
    """Create and return a Jira Issue from issue_dict"""

    # Import the bug and return the JIRA ID for said bug
    new_issue = jira.create_issue(fields=issue_dict)

    # Adding a link to the Launchpad bug into the JIRA entry
    link = {'url': bug.web_link, 'title': 'Launchpad Link'}
    jira.add_simple_link(new_issue, object=link)

    print("Created {}/browse/{}".format(jira.client_info(), new_issue.key))

    return new_issue


def lpToJiraBug(lp, jira, bug, project_id, opts):
    """Create JIRA issue at project_id for a given Launchpad bug"""
    
    if isBugInJira(jira, bug, project_id):
        return
    
    issue_dict = buildJiraIssue(lp, bug, project_id)
    if opts.label:
        # Add labels if specified
        issue_dict["labels"] = [opts.label]

    jira_issue = createJiraIssue(jira, issue_dict, bug)

    if not opts.no_lp_tag:
        # Add reference to the JIRA entry in the bugs on Launchpad
        bug.tags += [jira_issue.key.lower()]
        bug.lp_save()


def main():
    usage = """\
usage: lp-to-jira [options] bug-id project-id

Create JIRA entry for a given Launchpad bug ID

options:
    -e, --exists"
                Look if the Launchpad Bug has alreaady been imported
                print the JIRA issue ID if found
    -l, --label LABEL
                Add LABEL to the JIRA issue after creation

Examples:
    lp-to-jira 3215487 FR
    lp-to-jira -e 3215487 FR
    lp-to-jira -l ubuntu-meeting 3215487 PR
        """

    opt_parser = OptionParser(usage)
    opt_parser.add_option(
        '-l', '--label',
        dest='label',
    )
    opt_parser.add_option(
        '-e', '--exists',
        dest='exists',
        action='store_true'
    )

    opt_parser.add_option(
        '--no-lp-tag',
        dest='no_lp_tag',
        action='store_true'
    )

    opts, args = opt_parser.parse_args()

    # Connect to Launchpad API
    # TODO: catch exception if the Launchpad API isn't open
    lp = Launchpad.login_with('foundations', 'production', version='devel')

    # Connect to the JIRA API
    api = jira_api()
    jira = JIRA(api.server, basic_auth=(api.login, api.token))

    # Make sure there's 2 arguments
    if len(args) < 2:
        opt_parser.print_usage()
        return 1

    bug_number = args[0]
    project_id = args[1]
    bug = getLpBug(lp, bug_number)

    if opts.exists:
        # We are simply testing if the bug was already in JIRA
        if isBugInJira(jira, bug, project_id):
            return 0
        print("Launchpad Issue {} is not in JIRA project {}".format(
            bug.id, project_id))
        return 1

    # Create the Jira Issue
    lpToJiraBug(lp, jira, bug, project_id, opts)

    return 0


sys.exit(main())
