#!/usr/bin/python3
# The purpose of lp-to-jira is to take a launchad bug ID and
# create a new Entry in JIRA in a given project


import sys
import os
import json

from launchpadlib.launchpad import Launchpad
from jira import JIRA
from jira_api import jira_api

# Ex:
#     lp-to-JIRA bug_id
#     lp-to-JIRA 32165487 CI20


def usage():
    print("usage    lp-to-jira bug-id project-id")
    print("for ex:  lp-to-jira 3215487 PR007")


def main():
    # Make sure there's 2 arguments
    if len(sys.argv) != 3:
        usage()
        sys.exit(1)

    # TODO implement some better options parsing
    bug_number = sys.argv[1]
    project_id = sys.argv[2]
    jira_token_file = "{}/.jira.token".format(os.path.expanduser('~'))

    # 1. Connect to Launchpad API

    # TODO: catch exception if the Launchpad API isn't open
    lp = Launchpad.login_with('foundations', 'production', version='devel')

    # 2. Make sure the bug ID exist
    bug = None
    bug_pkg = None
    try:
        bug = lp.bugs[bug_number]
    except Exception:
        print("Couldn't find the Launchpad bug {}".format(bug_number))
        return 1

    if len(bug.bug_tasks) == 1:
        bug_pkg = bug.bug_tasks[0].bug_target_name.split()[0]
    else:
        for task in bug.bug_tasks:
            if "(Ubuntu)" in task.bug_target_name:
                bug_pkg = task.bug_target_name.split()[0]

    # 3. Connect to the JIRA API
    api = jira_api()
    jira = JIRA(api.server, basic_auth=(api.login, api.token))

    # 4. Make sure that there's no bug in JIRA with the same ID
    # than the Bug you're trying to import
    existing_issue = jira.search_issues(
        "project = \"{}\" AND summary ~ \"LP#{}\"".format(project_id, bug.id))

    if existing_issue:
        print("Launchpad Issue {} is already logged " +
              "in JIRA here {}/browse/{}".format(
                  bug_number,
                  api.server,
                  existing_issue[0].key))
        return 1

    # 5. import the bug and return the JIRA ID for said bug
    new_issue = jira.create_issue(
        project=project_id,
        summary='LP#{} [{}] {}'.format(bug.id, bug_pkg, bug.title),
        description=bug.description,
        issuetype={'name': 'Bug'})

    # 6. Adding a link to the Launchpad bug into the JIRA entry
    link = {'url': bug.web_link, 'title': 'Launchpad Link'}
    jira.add_simple_link(new_issue, object=link)

    # 7. Add reference to the JIRA entry in the bugs on Launchpad
    bug.tags += [new_issue.key.lower()]
    bug.lp_save()

    print("Created {}/browse/{}".format(api.server, new_issue.key))


main()
