title: LaunchPad to Jira Bug Importer
name: lp-to-jira
base: core24
version: '0.8'
summary: Command Line Interface to import Launchpad content into JIRA
description: |
  lp-to-jira allows you to import bug from a launchpad project into a JIRA
  project.

grade: stable
confinement: strict

parts:
  lp-to-jira:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    stage-packages:
      - python3-wheel
    python-packages:
      - jira
      - launchpadlib
    source: .

apps:
  lp-to-jira:
    command: bin/lp-to-jira
    plugs:
      - network
      - home
    environment:
      LANG: C.UTF-8

  report:
    command: bin/lp-to-jira-report
    plugs:
      - network
      - home
    environment:
      LANG: C.UTF-8
